### ISSUE TITLE
This plugin janks when sitemaps load

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-activity#19]
For background on janking, see http://jankfree.org/

I've used the chrome dev tools and now see just how terrible this plugin's update performance is when watching dozens of sitemaps load from a roster. (We bring this on ourselves by making these other cool plugins.)

Here is the root of the problem: `$item.empty()`. We start over with every update.
See this in the code: [github](https://github.com/fedwiki/wiki-plugin-activity/blob/929e9b6fd7145977f578d53698d3c090eb20cc11/client/activity.coffee#L141)

We could do a lot of work to incrementally update the dom as the occasional entry changes. But with all of the new features here that logic could get complex without some crazy dom management with, say, d3.

Here is a simpler solution: yield inside this loop: `for sites in pages`.
See this in the code: [github](https://github.com/fedwiki/wiki-plugin-activity/blob/929e9b6fd7145977f578d53698d3c090eb20cc11/client/activity.coffee#L175)

Unfortunately javascript doesn't have a yield instruction. Convention uses setTimeout to approximate yield. Folks with more complex needs have come up with the timer free version called setImmediate but it must be shimmed on most browsers. See https://github.com/YuzuJS/setImmediate

I'm still a little vague on how to iterate over large collections using callbacks without doing a tail call that might not be optimized. Do we have a stack depth problem?

WebWorkers have been proposed but that seems a different and equally heavy weight solution. Let's try the setImmediate solution.

**Comment by WardCunningham** [comment]
Another approach might be to assemble up the page contents into a large string and then insert that into the dom in one operation. In fact, this could be the best solution. Let's try that first.

**Comment by paul90** [comment]
How about a virtual DOM? 

[Matt-Esch/virtual-dom](https://github.com/Matt-Esch/virtual-dom) looks interesting, and not such a big step as React

**Comment by WardCunningham** [comment]
Let's try it.

**Comment by paul90** [comment]
branch created with a look at virtual-dom – it's interesting but not sure it is much better...

**Comment by paul90** [comment]
so, as well as using virtual-dom I have reworked the merge so that it doesn't start from scratch each time a sitemap is added to the neighbourhood.

Comparing the virtual-dom code against the existing show significant improvement. The diagrams below show first the existing code, followed by that using the virtual dom.

![existing - recent changes](https://cloud.githubusercontent.com/assets/1552489/9290680/8fcf6d5c-4393-11e5-885e-b1cbdaad497f.png)

![virt dom - recent changes](https://cloud.githubusercontent.com/assets/1552489/9290684/95d7ac0a-4393-11e5-9f8d-1c42c0ae8cf6.png)

**Comment by paul90** [comment]
Resolved by wiki-plugin-activity@0.2.5
