### ISSUE TITLE
Temporal ordering not always right for twins. Wrong sites marked as same.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-activity#23]
I've noticed that the newest site does not always show up on the right in the list of twins for a given title. I've yet to notice a pattern so this remains a mystery.

I noticed this morning that the Activity plugin marked the wrong sites to be of the same age when I forked the more recent modification of Modular Authentication. The evidence is here in the journals for the three pages. The misinterpretation, the wrong two flags are shown adjacent, even after a browser refresh of the lineup and sitemaps.

![screen shot 2015-09-08 at 7 33 17 am](https://cloud.githubusercontent.com/assets/12127/9737721/d983f6cc-55fc-11e5-95f2-f0d2002efd43.png)

**Comment by paul90** [comment]
looks as if the ordering of the flags got reversed in the recent virtual dom change - the newest is on the left now. This might explain why the spacer got placed on the wrong side of the flag, as well.

**Comment by paul90** [comment]
Fixed in + wiki-plugin-activity@0.2.7
