### ISSUE TITLE
Sitemap update results in duplication of site in activity view

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki-plugin-activity#26]
With fedwiki/wiki-client#158 which adds the update of the origin site's sitemap, we are getting duplication the origin site in the output from the activity plugin.
![7d9b5a24-111f-11e6-876e-e1e71d4bf855](https://cloud.githubusercontent.com/assets/1552489/15039384/8bf8807a-12a4-11e6-9c6f-423a886e590e.png)

This would appear to be caused by the [merge process](https://github.com/fedwiki/wiki-plugin-activity/blob/master/client/activity.coffee#L256) only catering for the merge new sitemaps, and not updates.

**Comment by WardCunningham** [comment]
Oops. I should have been writing my investigation of merge in this issue.

https://github.com/fedwiki/wiki-plugin-activity/issues/17#issuecomment-217176540

I notice that parsing but not merging has many test cases. The merge is complex so we will have to move with caution. My day job begins. I will return to this soon.

**Comment by WardCunningham** [comment]
Factoid: you can browse without having your origin's sitemap loaded. Consider:

http://asia.wiki.org/fed.wiki.org/welcome-visitors

which views the `fed.wiki.org` welcome page with the more up-to-date plugins from `asia.wiki.org`. Notice that no page from `asia.wiki.org` (or page citing same) was displayed so no `asia.wiki.org` sitemap loaded.
