### ISSUE TITLE
Twins not always ordered with newest to the right.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-activity#35]
This activity is formatted correctly when the activity plugin is open while sitemaps are loaded.

![image](https://user-images.githubusercontent.com/12127/42412513-9d428896-81c2-11e8-8c1d-6e633f5e20a7.png)

But when calling up the same page a second time, the order of sites for a page, and thus the order of pages changes.

![image](https://user-images.githubusercontent.com/12127/42412532-e6af1df0-81c2-11e8-9743-8c382c929ec2.png)

**Comment by WardCunningham** [comment]
Understanding this issue was made more difficult by the LIMIT to 7 days applied in the plugin configuration. This caused pages to simply disappear.

http://found.ward.bay.wiki.org/view/welcome-visitors/view/the-good-parts/view/recent-changes

**Comment by paul90** [comment]
Fix in + wiki-plugin-activity@0.3.3
